apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: round-robin-test
spec:
  host: machine-learning
  subsets:
    - name: v1
      labels:
        version: v1
      trafficPolicy:
        loadBalancer:
          simple: RANDOM    
